# Generated by Django 4.1 on 2022-08-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_budgetentry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='entry_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_of_entry', to='budget_app.category'),
        ),
    ]
